export {default as HomePage} from './component/home/Home'
export {default as LoginPage} from './component/auth/login/Login'
export {default as ForgotPasswordPage} from './component/auth/forgot-password/ForgotPassword.jsx'
export {default as SelectUserPage} from './component/auth/select-user/SelectUser.jsx'
// export {default as DashboardMainPage} from './component/dashboard/Dashboard'
export {default as UserPage} from './component/user/User'
export {default as UserArchivePage} from './component/user-archive/UserArchive'
export {default as RollPage} from './component/roll/Roll'
export {default as AddRolePage} from './component/add-role/AddRole'
export {default as Customers} from './component/customers/Customers'
export {default as CustomerArchivePage} from './component/customer-archive/CustomerArchive'
export {default as CustomerObjectArchivePage} from './component/objet-archive/CustomerObjectArchiveMain'
export {default as CreateResidentsPage} from './component/create-residents/CreateResidents'
export {default as CreateResidentsArchiveMain} from './component/create-residents-archive/CreateResidentsArchiveMain'
export {default as CreateUserPage} from './component/create-user/CreateUser'
export {default as ReportingPage} from './component/reporting/Reporting'
export {default as ReportingPdfVersionPage} from './component/reporting-pdf-version/ReportingPdfVersion'
export {default as Monitoring} from './component/monitoring/Monitoring'
export {default as UserManagementMainPage} from './component/user-management-main/UserManagementMain'



